// <auto-generated />
namespace School.Migrations.SchoolMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TeacherRelationtoclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeacherRelationtoclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021809146_Teacher Relation to class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
